name = "SIMDIndexing"
uuid = "dc12af0d-3b10-50fe-b0dd-a5d243725f40"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
SIMD = "≥ 2.3"
julia = "≥ 0.7"
